export { default as DashboardView } from './views/DashboardView'
export { default as UsersView } from './views/UsersView'
export { default as UserDetailView } from './views/UserDetailView'
export { default as MechanicsView } from './views/MechanicsView'
export { default as WorkshopsView } from './views/WorkshopsView'
export { default as BookingsView } from './views/BookingsView'
export { default as ServicesView } from './views/ServicesView'
export { default as ReviewsView } from './views/ReviewsView'
export { default as SettingsView } from './views/SettingsView'
export { default as JobsView } from './views/JobsView'
export { default as JobDetailView } from './views/JobDetailView'
export { default as AdminHeader } from './components/AdminHeader'
export { default as AdminSidebar } from './components/AdminSidebar'
export * from './services/admin.service'
export * from './models/admin.model'
