export { default as HomeView } from './views/HomeView'
export { default as ProfileView } from './views/ProfileView'
export { default as ShopView } from './views/ShopView'
export { default as AppointmentsView } from './views/AppointmentsView'
export { default as AddCarView } from './views/AddCarView'
export { default as CompletedRepairsView } from './views/CompletedRepairsView'
export { default as RepairHistoryView } from './views/RepairHistoryView'
export { default as RepairDetailsView } from './views/RepairDetailsView'
export { default as BookAppointmentModal } from './components/BookAppointmentModal'
export { default as CreateAppointmentModal } from './components/CreateAppointmentModal'
export * from './services/user.service'
export * from './models/user.model'
